### ISSUE TITLE
Fails to compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by planetceres** [AcutronicRobotics/robotiq_modular_gripper#1]
Following the installation instructions on Ubuntu 18.04 with ROS Melodic, the project fails to compile with `colcon build --merge-install`. 

```
Starting >>> hrim_actuator_gripper_srvs
--- stderr: cv_bridge                                                      
In file included from /home/user/ros2_mara_ws/src/vision_opencv/cv_bridge/src/cv_bridge.cpp:37:0:
/home/user/ros2_mara_ws/src/vision_opencv/cv_bridge/include/cv_bridge/cv_bridge.h:40:10: fatal error: sensor_msgs/msg/image.hpp: No such file or directory
 #include <sensor_msgs/msg/image.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/cv_bridge.dir/cv_bridge.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/cv_bridge.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 92, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 72, in build
    additional_hooks=additional_hooks)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 103, in build
    if rc and rc.returncode:
AttributeError: 'int' object has no attribute 'returncode'
---
Failed   <<< cv_bridge	[ Exited with code 1 ]
Aborted  <<< camera_calibration_parsers                                               
Aborted  <<< gazebo_dev                                                               
--- stderr: gazebo_msgs                                                               
Message interface 'geometry_msgs/Wrench' contains an unknown field type: geometry_msgs/Wrench[] wrenches
Message interface 'geometry_msgs/Wrench' contains an unknown field type: geometry_msgs/Wrench[] wrenches
make[2]: *** [rosidl_typesupport_introspection_c/gazebo_msgs/msg/contact_state__rosidl_typesupport_introspection_c.h] Error 1
make[1]: *** [CMakeFiles/gazebo_msgs__rosidl_typesupport_introspection_c.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [rosidl_typesupport_fastrtps_cpp/gazebo_msgs/msg/contact_state__rosidl_typesupport_fastrtps_cpp.hpp] Error 1
make[1]: *** [CMakeFiles/gazebo_msgs__rosidl_typesupport_fastrtps_cpp.dir/all] Error 2
Message interface 'geometry_msgs/Wrench' contains an unknown field type: geometry_msgs/Wrench[] wrenches
make[2]: *** [rosidl_typesupport_introspection_cpp/gazebo_msgs/msg/contact_state__rosidl_typesupport_introspection_cpp.hpp] Error 1
make[1]: *** [CMakeFiles/gazebo_msgs__rosidl_typesupport_introspection_cpp.dir/all] Error 2
make: *** [all] Error 2
---
Aborted  <<< gazebo_msgs
Aborted  <<< hrim_generic_msgs                                                         
Aborted  <<< hrim_actuator_gripper_srvs
--- stderr: image_transport                                                     
CMake Error at CMakeLists.txt:60 (pluginlib_export_plugin_description_file):
  Unknown CMake command "pluginlib_export_plugin_description_file".

---
Aborted  <<< image_transport
--- stderr: control_msgs                                         
Message interface 'std_msgs/Header' contains an unknown field type: std_msgs/Header header
make[2]: *** [rosidl_typesupport_fastrtps_cpp/control_msgs/msg/gripper_command__rosidl_typesupport_fastrtps_cpp.hpp] Error 1
make[2]: *** Deleting file 'rosidl_typesupport_fastrtps_cpp/control_msgs/msg/gripper_command__rosidl_typesupport_fastrtps_cpp.hpp'
make[1]: *** [CMakeFiles/control_msgs__rosidl_typesupport_fastrtps_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Message interface 'std_msgs/Header' contains an unknown field type: std_msgs/Header header
make[2]: *** [rosidl_typesupport_introspection_cpp/control_msgs/msg/gripper_command__rosidl_typesupport_introspection_cpp.hpp] Error 1
make[2]: *** Deleting file 'rosidl_typesupport_introspection_cpp/control_msgs/msg/gripper_command__rosidl_typesupport_introspection_cpp.hpp'
make[1]: *** [CMakeFiles/control_msgs__rosidl_typesupport_introspection_cpp.dir/all] Error 2
Message interface 'std_msgs/Header' contains an unknown field type: std_msgs/Header header
make[2]: *** [rosidl_typesupport_introspection_c/control_msgs/msg/gripper_command__rosidl_typesupport_introspection_c.h] Error 1
make[2]: *** Deleting file 'rosidl_typesupport_introspection_c/control_msgs/msg/gripper_command__rosidl_typesupport_introspection_c.h'
make[1]: *** [CMakeFiles/control_msgs__rosidl_typesupport_introspection_c.dir/all] Error 2
make: *** [all] Error 2
---
Aborted  <<< control_msgs


```

**Comment by nzlz** [comment]
Hi @planetceres ,
Apologies for the long wait, this issue went completely unnoticed. Are you still facing this issue? I would recommend trying the latest changed, since we have updated multiple packages since.
